### ISSUE TITLE
Show Open Source Licenses in About Page

### ISSUE THREAD

**Issue by rumaan** [rumaan/file.io-Android-Client#9]

**Comment by deepakkumardk** [comment]
I would like to work on it.

**Comment by rumaan** [comment]
@deepakkumardk Oh hello! You can create a new activity that shows all the libraries used in this project as a list for starters. A simple scrollview with text would be awesome!

**Comment by deepakkumardk** [comment]
I am planning to use [material-about-library](https://github.com/daniel-stoneuk/material-about-library) to show all the license.

**Comment by rumaan** [comment]
yeah sure! that would be great!

**Comment by deepakkumardk** [comment]
okay, great I am working on it.
